import React from "react";
import Nav from "./components/Nav";
import "./globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";

export const metadata = {
  title: "Nextjs Ecommerce",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
}

export default async function RootLayout({
  children,
}: Props) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className="mx-64">
        <Nav
          user={session?.user}
          expires={session?.expires as string}
        />
        {children}
      </body>
    </html>
  );
}

